name: barcode_scan_javalite
description: A flutter plugin for scanning 2D barcodes and QRCodes via camera.
version: 1.0.0
homepage: https://github.com/sonvp/flutter_barcode_reader

dependencies:
  protobuf: ^2.0.0
  flutter:
    sdk: flutter

dev_dependencies:
  effective_dart: ^1.2.0

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0 <2.0.0"

flutter:
  plugin:
    platforms:
      android:
        package: de.mintware.barcode_scan
        pluginClass: BarcodeScanPlugin
      ios:
        pluginClass: SwiftBarcodeScanPlugin